/**
 * @file products.ts
 * @description Mock data produk Modesy Marketplace sesuai visual referensi asli
 */

import { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    title: "Cat Head Print Shoulder Bag",
    slug: "cat-head-print-shoulder-bag",
    price: 18.5,
    original_price: 26.0,
    rating: 4.9,
    reviews_count: 42,
    image_url: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80",
    category_name: "Bags",
    is_featured: true,
    is_special_offer: true,
    discount_percentage: 29,
    stock: 25,
  },
  {
    id: "prod-2",
    title: "Bohemian Print Kimono Cardigan",
    slug: "bohemian-print-kimono-cardigan",
    price: 32.0,
    original_price: 45.0,
    rating: 4.8,
    reviews_count: 88,
    image_url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80",
    category_name: "Clothing",
    is_featured: true,
    is_special_offer: true,
    discount_percentage: 29,
    stock: 18,
  },
  {
    id: "prod-3",
    title: "Black Lace Trim Evening Blouse",
    slug: "black-lace-trim-evening-blouse",
    price: 28.5,
    original_price: 40.0,
    rating: 4.7,
    reviews_count: 65,
    image_url: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80",
    category_name: "Clothing",
    is_featured: true,
    is_special_offer: true,
    discount_percentage: 29,
    stock: 30,
  },
  {
    id: "prod-4",
    title: "Sleeveless Floral Cocktail Dress",
    slug: "sleeveless-floral-cocktail-dress",
    price: 45.0,
    original_price: 65.0,
    rating: 4.9,
    reviews_count: 112,
    image_url: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&auto=format&fit=crop&q=80",
    category_name: "Clothing",
    is_featured: true,
    is_special_offer: true,
    discount_percentage: 31,
    stock: 22,
  },
  {
    id: "prod-5",
    title: "Waterproof Travel Laptop Backpack",
    slug: "waterproof-travel-laptop-backpack",
    price: 54.0,
    original_price: 80.0,
    rating: 4.8,
    reviews_count: 140,
    image_url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80",
    category_name: "Bags",
    is_featured: true,
    is_special_offer: true,
    discount_percentage: 33,
    stock: 40,
  },
  {
    id: "prod-6",
    title: "Urban Streetwear Knit Running Shoes",
    slug: "urban-streetwear-knit-running-shoes",
    price: 48.0,
    original_price: 72.0,
    rating: 4.6,
    reviews_count: 75,
    image_url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80",
    category_name: "Shoes",
    is_featured: true,
    is_special_offer: true,
    discount_percentage: 33,
    stock: 15,
  },
  {
    id: "prod-7",
    title: "Vintage Botanical Print Scarf",
    slug: "vintage-botanical-print-scarf",
    price: 16.0,
    original_price: 24.0,
    rating: 4.9,
    reviews_count: 53,
    image_url: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&auto=format&fit=crop&q=80",
    category_name: "Accessories",
    is_featured: true,
    is_special_offer: false,
    stock: 35,
  },
  {
    id: "prod-8",
    title: "Decorative Geometric Velvet Pillows",
    slug: "decorative-geometric-velvet-pillows",
    price: 22.5,
    original_price: 32.0,
    rating: 4.8,
    reviews_count: 67,
    image_url: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80",
    category_name: "Home & Living",
    is_featured: true,
    is_special_offer: false,
    stock: 50,
  },
  {
    id: "prod-9",
    title: "Handmade Suede Ankle Boots",
    slug: "handmade-suede-ankle-boots",
    price: 68.0,
    original_price: 95.0,
    rating: 4.9,
    reviews_count: 84,
    image_url: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop&q=80",
    category_name: "Shoes",
    is_featured: true,
    is_special_offer: false,
    stock: 14,
  },
  {
    id: "prod-10",
    title: "Summer Wide-Brim Sun Straw Hat",
    slug: "summer-wide-brim-sun-straw-hat",
    price: 19.99,
    original_price: 28.0,
    rating: 4.7,
    reviews_count: 39,
    image_url: "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600&auto=format&fit=crop&q=80",
    category_name: "Accessories",
    is_featured: true,
    is_special_offer: false,
    stock: 28,
  },
  {
    id: "prod-11",
    title: "Tactical Lightweight Hiking Boots",
    slug: "tactical-lightweight-hiking-boots",
    price: 79.0,
    original_price: 110.0,
    rating: 4.8,
    reviews_count: 92,
    image_url: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600&auto=format&fit=crop&q=80",
    category_name: "Shoes",
    is_featured: true,
    is_special_offer: false,
    stock: 20,
  },
  {
    id: "prod-12",
    title: "Navy Blue Canvas Crossbody Messenger Bag",
    slug: "navy-blue-canvas-crossbody-messenger-bag",
    price: 36.0,
    original_price: 52.0,
    rating: 4.8,
    reviews_count: 48,
    image_url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop&q=80",
    category_name: "Bags",
    is_featured: true,
    is_special_offer: false,
    stock: 30,
  },
  {
    id: "prod-13",
    title: "Organic Cotton Plain T-Shirt",
    slug: "organic-cotton-plain-t-shirt",
    price: 15.0,
    original_price: 22.0,
    rating: 4.6,
    reviews_count: 130,
    image_url: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80",
    category_name: "Clothing",
    is_featured: true,
    is_special_offer: false,
    stock: 60,
  },
  {
    id: "prod-14",
    title: "Outdoor Golden Retriever Art Print",
    slug: "outdoor-golden-retriever-art-print",
    price: 25.0,
    original_price: 35.0,
    rating: 5.0,
    reviews_count: 24,
    image_url: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&auto=format&fit=crop&q=80",
    category_name: "Craft",
    is_featured: true,
    is_special_offer: false,
    stock: 12,
  },
  {
    id: "prod-15",
    title: "Vintage Sunset Mountain Landscape Canvas",
    slug: "vintage-sunset-mountain-landscape-canvas",
    price: 42.0,
    original_price: 60.0,
    rating: 4.9,
    reviews_count: 36,
    image_url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80",
    category_name: "Home & Living",
    is_featured: true,
    is_special_offer: false,
    stock: 15,
  },
  {
    id: "prod-16",
    title: "Classic Denim Light Wash Button-Down Shirt",
    slug: "classic-denim-light-wash-button-down-shirt",
    price: 38.0,
    original_price: 55.0,
    rating: 4.8,
    reviews_count: 78,
    image_url: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&auto=format&fit=crop&q=80",
    category_name: "Clothing",
    is_featured: true,
    is_special_offer: false,
    stock: 25,
  },
  {
    id: "prod-17",
    title: "Tall Ship Ocean Sailing Oil Canvas Painting",
    slug: "tall-ship-ocean-sailing-oil-canvas-painting",
    price: 85.0,
    original_price: 120.0,
    rating: 5.0,
    reviews_count: 19,
    image_url: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=600&auto=format&fit=crop&q=80",
    category_name: "Vintage",
    is_featured: true,
    is_special_offer: false,
    stock: 8,
  },
  {
    id: "prod-18",
    title: "Handwoven Round Straw Rattan Tote Bag",
    slug: "handwoven-round-straw-rattan-tote-bag",
    price: 29.5,
    original_price: 45.0,
    rating: 4.9,
    reviews_count: 94,
    image_url: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&auto=format&fit=crop&q=80",
    category_name: "Accessories",
    is_featured: true,
    is_special_offer: false,
    stock: 32,
  },
];
